CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    category VARCHAR(50),
    subcategory VARCHAR(50),
    sku VARCHAR(50) UNIQUE,
    barcode VARCHAR(100),
    weight DECIMAL(8,3),
    purity VARCHAR(20),
    metal_type VARCHAR(30),
    stone_type VARCHAR(30),
    stone_weight DECIMAL(8,3),
    cost_price DECIMAL(10,2),
    selling_price DECIMAL(10,2),
    discount_percentage DECIMAL(5,2) DEFAULT 0,
    stock_quantity INTEGER DEFAULT 0,
    reorder_level INTEGER DEFAULT 10,
    supplier VARCHAR(100),
    is_active BOOLEAN DEFAULT true,
    image_url VARCHAR(255),
    back_image_url VARCHAR(255)
);